spring.datasource.url=jdbc:mysql://localhost:3306/pietos_bgv?sslMode=DISABLED
spring.datasource.username=root
spring.datasource.password=Pietos@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# JWT Configuration
jwt.secret=8aB3fK91LmP2QwX7RsT5YuV8NzE6HdJ4QaC9MfG2XpW1LsR8Tk
jwt.expiration=86400000

# Meta WhatsApp Cloud API
whatsapp.access-token=EAAX3UGroYBgBSL6WhLZC8ROH5vZC14xBRnhDeKJZCKsqLbiZCpySB7xxmtvrJYOQUPu8pZBBjXcDB3v3lguy3MSm6s908z5537qilVYR4XPfuEjAcGeA6UqXYXXCCMZCzIqpHu1fZBxqA6aFCAx09FFwwnIuuimcmJMoCPCNcur1wTd11sXxWpdyDXDeIz6RZBEZAaXYgRl6ilg9Srah2SWx4HluHHDktzLiwkZAK3n7vXI7sL6ORe6fwzP43kFZBLfvUQuIMHOh68UZA9cGQtxZBPQZDZD
whatsapp.phone-number-id=1160783573792394 
whatsapp.business-account-id=1996406941244377
whatsapp.api-version=v23.0


file.upload-dir=C:/bgv/uploads

app.encryption.key=HT291kAHI5pI7IWX3Hfyj5PiYTrC0XSA+3NOsoKRDXU=

tesseract.path=C:/Program Files/Tesseract-OCR/tesseract.exe
tesseract.language=eng