package com.pietos.bgv.entity.cases;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.pietos.bgv.entity.ClientInformation;
import com.pietos.bgv.entity.ClientLocation;
import com.pietos.bgv.entity.ClientPackage;
import com.pietos.bgv.entity.SystemUser;
import com.pietos.bgv.enums.CaseStatus;
import com.pietos.bgv.enums.EmploymentType;

import jakarta.persistence.*;

@Entity
@Table(
    name = "cases",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_case_ref",
            columnNames = "case_ref"
        )
    }
)
public class Case {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Case Reference - generated by backend
    @Column(name = "case_ref", nullable = false, unique = true)
    private String caseRef;

    // Client
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id", nullable = false)
    private ClientInformation clientInformation;

    // Client Location
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id", nullable = false)
    private ClientLocation location;

    // Case Dates
    @Column(name = "case_received_date", nullable = false)
    private LocalDate caseReceivedDate;

    @Column(name = "case_in_date", nullable = false)
    private LocalDate caseInDate;

    @Column(name = "case_due_date")
    private LocalDate caseDueDate;

    // Employment Type
    // PRE_EMPLOYMENT / POST_EMPLOYMENT
    @Enumerated(EnumType.STRING)
    @Column(name = "employment", nullable = false)
    private EmploymentType employment;

    // Candidate Details
    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "middle_name")
    private String middleName;

    @Column(name = "last_name", nullable = false)
    private String lastName;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Column(name = "father_name")
    private String fatherName;

    @Column(name = "client_employee_id")
    private String clientEmployeeId;

    @Column(name = "date_of_joining")
    private LocalDate dateOfJoining;

    @Column(name = "mobile_number")
    private String mobileNumber;

    @Column(name = "email")
    private String email;

    @Column(name = "gender")
    private String gender;

    // Case Status
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private CaseStatus status;

    // Report
    @Column(name = "report")
    private String report;

    // Audit
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private SystemUser createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "updated_by")
    private SystemUser updatedBy;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_package_id")
    private ClientPackage clientPackage;


    // Default Constructor
    public Case() {
    }


    @PrePersist
    public void prePersist() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    public void preUpdate() {
        updatedAt = LocalDateTime.now();
    }


    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCaseRef() {
        return caseRef;
    }

    public void setCaseRef(String caseRef) {
        this.caseRef = caseRef;
    }

    public ClientInformation getClientInformation() {
        return clientInformation;
    }

    public void setClientInformation(ClientInformation clientInformation) {
        this.clientInformation = clientInformation;
    }

    

    public ClientLocation getLocation() {
		return location;
	}


	public void setLocation(ClientLocation location) {
		this.location = location;
	}


	public LocalDate getCaseReceivedDate() {
        return caseReceivedDate;
    }

    public void setCaseReceivedDate(LocalDate caseReceivedDate) {
        this.caseReceivedDate = caseReceivedDate;
    }

    public LocalDate getCaseInDate() {
        return caseInDate;
    }

    public void setCaseInDate(LocalDate caseInDate) {
        this.caseInDate = caseInDate;
    }

    public LocalDate getCaseDueDate() {
        return caseDueDate;
    }

    public void setCaseDueDate(LocalDate caseDueDate) {
        this.caseDueDate = caseDueDate;
    }

    public EmploymentType getEmployment() {
        return employment;
    }

    public void setEmployment(EmploymentType employment) {
        this.employment = employment;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getFatherName() {
        return fatherName;
    }

    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    public String getClientEmployeeId() {
        return clientEmployeeId;
    }

    public void setClientEmployeeId(String clientEmployeeId) {
        this.clientEmployeeId = clientEmployeeId;
    }

    public LocalDate getDateOfJoining() {
        return dateOfJoining;
    }

    public void setDateOfJoining(LocalDate dateOfJoining) {
        this.dateOfJoining = dateOfJoining;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

  

    public CaseStatus getStatus() {
		return status;
	}


	public void setStatus(CaseStatus status) {
		this.status = status;
	}


	public String getReport() {
        return report;
    }

    public void setReport(String report) {
        this.report = report;
    }

    public SystemUser getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(SystemUser createdBy) {
        this.createdBy = createdBy;
    }

    public SystemUser getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(SystemUser updatedBy) {
        this.updatedBy = updatedBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public ClientPackage getClientPackage() {
        return clientPackage;
    }

    public void setClientPackage(ClientPackage clientPackage) {
        this.clientPackage = clientPackage;
    }
}